name: parser tests

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: install golang
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: go test
      run: go test -v -cover ./...
